# Generated by Django 4.0.3 on 2022-03-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='это поле автоматически заполнится', editable=False, max_length=100, verbose_name='Название Бота')),
                ('link', models.URLField(blank=True, default='это поле автоматически заполнится', editable=False, max_length=150, verbose_name='Ссылка на бот')),
                ('username', models.CharField(blank=True, default='это поле автоматически заполнится', editable=False, max_length=100)),
                ('tid', models.CharField(blank=True, default='это поле автоматически заполнится', editable=False, max_length=100)),
                ('token', models.CharField(help_text='вставьте токен, полученный у BotFather', max_length=150, verbose_name='Токен Бота')),
                ('server_url', models.CharField(help_text='https://<название домена>', max_length=200, verbose_name='Webhook Url')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Настройки Telegram бота',
                'verbose_name_plural': 'Настройки Telegram ботов',
            },
        ),
    ]
