# Generated by Django 4.0.3 on 2022-04-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(editable=False, max_length=30, verbose_name='User id')),
                ('user_name', models.CharField(editable=False, max_length=50, verbose_name='User name')),
                ('first_name', models.CharField(blank=True, editable=False, max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, editable=False, max_length=50, verbose_name='Last name')),
                ('is_bot', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Registered User',
                'verbose_name_plural': 'Registered Users',
            },
        ),
        migrations.AlterModelOptions(
            name='botconfig',
            options={'verbose_name': 'Telegram Bot Settings', 'verbose_name_plural': 'Telegram Bots Settings'},
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='link',
            field=models.URLField(blank=True, default='default field', editable=False, max_length=150, verbose_name='Bot link'),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='tid',
            field=models.CharField(blank=True, default='default field', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='title',
            field=models.CharField(blank=True, default='default field', editable=False, max_length=100, verbose_name='Bot name'),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='token',
            field=models.CharField(help_text='Put bot token, received from BotFather', max_length=150, verbose_name='Bot Token'),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='username',
            field=models.CharField(blank=True, default='default field', editable=False, max_length=100),
        ),
    ]
