# Generated by Django 4.0.3 on 2022-04-21 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbot_base', '0002_users_alter_botconfig_options_alter_botconfig_link_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='BotUsers',
        ),
    ]
