# Generated by Django 4.0.3 on 2022-04-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot_base', '0003_rename_users_botusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botusers',
            name='user_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='User id'),
        ),
    ]
