# Generated by Django 4.0.3 on 2022-04-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot_base', '0005_alter_botusers_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botusers',
            name='id',
        ),
        migrations.AlterField(
            model_name='botusers',
            name='user_id',
            field=models.CharField(blank=True, max_length=30, primary_key=True, serialize=False, verbose_name='User id'),
        ),
    ]
