# Generated by Django 4.0.3 on 2022-04-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot_base', '0006_remove_botusers_id_alter_botusers_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botusers',
            name='first_name',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='botusers',
            name='last_name',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='botusers',
            name='user_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='User id'),
        ),
    ]
