# Generated by Django 4.0.3 on 2022-04-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot_base', '0008_alter_botusers_first_name_alter_botusers_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botusers',
            name='user_id',
            field=models.CharField(editable=False, max_length=30, primary_key=True, serialize=False, verbose_name='User id'),
        ),
        migrations.AlterField(
            model_name='botusers',
            name='user_name',
            field=models.CharField(default='', editable=False, max_length=50, verbose_name='User name'),
        ),
    ]
