# Generated by Django 4.0.3 on 2022-04-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot_base', '0009_alter_botusers_user_id_alter_botusers_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(editable=False, max_length=30, verbose_name='User id')),
                ('user_name', models.CharField(default='', editable=False, max_length=50, verbose_name='User name')),
                ('first_name', models.CharField(default='', editable=False, max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(default='', editable=False, max_length=50, verbose_name='Last name')),
                ('amount', models.IntegerField(editable=False, verbose_name='Amount of payment')),
                ('currency', models.CharField(editable=False, max_length=50, verbose_name='Currency of payment')),
                ('is_vip', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User Payments',
                'verbose_name_plural': 'Users Payments',
            },
        ),
        migrations.AddField(
            model_name='botusers',
            name='free_items',
            field=models.IntegerField(default=10, verbose_name='Amount of payment'),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='server_url',
            field=models.CharField(help_text='https://<domain>', max_length=200, verbose_name='Webhook Url'),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='token',
            field=models.CharField(help_text='Put bot token from BotFather', max_length=150, verbose_name='Bot Token'),
        ),
        migrations.AlterField(
            model_name='botusers',
            name='first_name',
            field=models.CharField(default='', editable=False, max_length=50, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='botusers',
            name='last_name',
            field=models.CharField(default='', editable=False, max_length=50, verbose_name='Last name'),
        ),
    ]
