# Generated by Django 4.0.3 on 2022-04-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot_base', '0010_userpayments_botusers_free_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botusers',
            name='free_items',
        ),
        migrations.AddField(
            model_name='botusers',
            name='free_attempts',
            field=models.IntegerField(default=10, verbose_name='Free attempts '),
        ),
    ]
