# Generated by Django 4.0.3 on 2022-06-25 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbot_base', '0011_remove_botusers_free_items_botusers_free_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botusers',
            name='free_attempts',
        ),
    ]
